### ISSUE TITLE
Unable to import component

### ISSUE THREAD

**Issue by se7en7777777** [And3rsL/Deebot-for-hassio#60]
Configuration.yaml (Remember to delete your credentials)
deebot:
   username: *****
   password: *****
   country: cn
   continent: ww
   deviceid:
     - E05N1*****   
System Informations:

Device: Deebot 907
Home Assistant Version: 0.115.1
Hardware: Pi 3b+
Home Assistant Installation: Home Assistant OS

Logger: homeassistant.setup
Source: setup.py:138

Setup failed for deebot: Unable to import component: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.7 from "/usr/bin/python3" * The NumPy version is: "1.19.4" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

**Comment by edenhaus** [comment]
Please provide all information requested by the template. See https://github.com/And3rsL/Deebot-for-hassio/issues/29

**Comment by se7en7777777** [comment]
sudo apt-get install libatlas-base-dev
its oky~!
thanks

**Comment by andrearomanoif** [comment]
I was having the same problem after I updated to Deebot-for-Home-Assistant version 3.0.1: Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory.

I followed the proposed solution with the command "sudo apt-get install libatlas-base-dev".
After the installation I had the following problem:
Component error: deebot -

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

* The Python version is: Python3.9 from "/srv/homeassistant/bin/python3.9"
* The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29 'not found (required by /srv/homeassistant/lib/python3.9/site-packages/numpy/core/_multiarray_umath .cpython-39-arm-linux-gnueabihf.so)

I have tried several solutions on the net but it keeps telling me that GLIC_2.29 is not present.
The problem continues even if I revert to version 2.1.2 or earlier.

Is there a solution ???

My home assistant is the core version and runs on raspberry py 4 with python 3.9.
